import Head from 'next/head'
import Image from 'next/image'
import Header from '@/components/Header/Header.js'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import HomeImage from '@/public/images/home-image.svg'
const inter = Inter({ subsets: ['latin'] })
import {Authenticator } from '@aws-amplify/ui-react'
import "@aws-amplify/ui-react/styles.css"
import awsconfig from '../aws-exports'
import { Amplify } from 'aws-amplify'
Amplify.configure(awsconfig)

export default function Index() {
  return (
    <Authenticator>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header/>
        <div className='flex flex-1 items-center justify-around px-20 mb-10'>
          <div className={'max-w-2xl'}>
              <h1 className='text-yellow-200 font-bold text-5xl'>Organize suas tarefas!</h1>
              <h6 className='text-2xl'>Bem-vindo ao DoitDocker, o gerenciador de tarefas que pode ajudar a melhorar sua produtividade. Com nosso software fácil de usar, você pode organizar suas tarefas diárias, definir prazos e acompanhar seu progresso em tempo real. Deixe o DoitDocker ajudá-lo a alcançar suas metas e objetivos!</h6>
          </div>
          <div>
          <Image src={HomeImage} ></Image>
          </div>
        </div>
      </main>
    </Authenticator>
  )
}
